models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
        - from: inputs/rsOrderCompleted
var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: is_churned_7_days
          select: case when {{user.Var("days_since_last_seen")}} > 7 then 1 else 0 end # Same condition as in the package project
      - entity_var:
          name: days_since_last_seen
          select: "{{macro_datediff('{{user.Var(\"max_timestamp_bw_tracks_pages\")}}')}}"
          default: 0
      - entity_var:
          name: max_timestamp_tracks
          select: max(timestamp)
          from: inputs/rsTracks
      - entity_var:
          name: max_timestamp_pages
          select: max(timestamp)
          from: inputs/rsPages
          description: The total value of products that are part of the last transaction.
      - entity_var:
          name: random_date_feature
          select: "{{macro_random_date_feature()}}"
      - entity_var:
          name: random_timestamp_feature
          select: TIMESTAMP '2023-11-04 12:34:56'
      - entity_var:
          name: random_tz_aware_feature
          select: "{{macro_random_tz_aware_feature()}}"
      - entity_var:
          name: random_tz_unaware_feature
          select: "{{macro_random_tz_unaware_feature()}}"
      - entity_var:
          name: random_high_cardinal_feature
          select: any_value(user_id)
          from: inputs/rsPages
